version: '3.8'
services:
  backend:
    container_name: perguntasback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - mongo_conect=mongodb+srv://<abc>:<senha>@cluster0.kwbxhtb.mongodb.net/peguntas?retryWrites=true&w=majority
      - mongo_data=perguntas
